### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by OMilosh** [mlvlab/SCDM#1]
Hello! Thank you for the article. 
I’m trying to train model on a custom dataset (I calculated “psiphi” for it and I have 11 classes in my dataset. ). 
You use function q_sample in the function training_losses in the gaussian_diffusion.py at 117 line:
` x_t = self.q_sample(x_start, t, noise=noise)`
But q_sample function have parameter "option" (default = "").  In this case `if option.split('_')[2] == 'classwise':` at line 255 will cause error. I have hardcoded this option with "discrete_zero_classwise" but there are new error:
`File ".../SCDM/guided_diffusion/gaussian_diffusion.py", line 261, in q_sample
classwise_gammas = 1.0 - (x_start.permute(0,2,3,1)*tmp).sum(dim=3)
RuntimeError: The size of tensor a (3) must match the size of tensor b (11) at non-singleton dimension 3`.
Can you help me with this error? Or maybe you will provide code for psiphi calculation?

**Comment by OMilosh** [comment]
I tried to train model on ADE dataset and get the same errors. Is something wrong with tensor shapes?

**Comment by dewyeon** [comment]
Hi! Thanks for reaching out and for your interest in our paper.
We've just updated the code in `q_sample()` function. 
I've also sent a response to your email with further details.

**Comment by areyoukamil** [comment]
Dear @OMilosh how did you compute psiphi?
