### ISSUE TITLE
 Inquiry About the Calculation of psiphi for Custom Dataset

### ISSUE THREAD

**Issue by lf0099** [mlvlab/SCDM#2]
First of all, thank you for sharing this amazing project! I’m currently trying to apply it to my own custom dataset, but I’m unsure about how to compute the ’psiphi‘.

Could you kindly provide some guidance on how these values are calculated for a custom dataset? Are there specific formulas or steps that I should follow? Any advice or reference to relevant documentation would be greatly appreciated.

**Comment by areyoukamil** [comment]
Would be nice to have a script/guidance to generate custom_psiphi otherwise it is not possible to run it with a custom dataset at this moment

**Comment by dewyeon** [comment]
Hi! Thanks for reaching out and for your interest in our paper.

Currently, there are no specific scripts available to calculate $\psi$ and $\phi$. However, the examples below provide a guide on how to compute them for a custom dataset. The point is to slow down the diffusion of classes with smaller areas and lower frequencies, and you can freely implement the calculations as you prefer.

Here's a guide to calculating the values:

## Calculating $\psi_c$
$\psi_c$ represents the inverse of the average ratio of the total image pixels to the class pixels. As the average area of class c decreases, $\psi_c$ increases:

$\psi_c = \text{avg} \left(\frac{\text{(pixels for class c in the image)}}{\text{(total pixels in an image)}}\right)^{-1}$ 

### Example:
- The class 'bottle' appears in 3 training images with 100, 125, and 80 pixels, respectively.
- The total image pixels for these images are 65520, 60040, and 65525.
$\psi_{\text{bottle}} = \text{avg}\left(\frac{100}{65520}, \frac{126}{60040}, \frac{80}{65525}\right)^{-1}$

## Calculating $\phi_c$
$\phi_c$ measures the log inverse frequency of a class in the training set. A larger $\phi_c$ value corresponds to a class that rarely appears in the dataset:

$\phi_c = \log \left( \frac{\text{(num of total training images)}}{\text{(num of images containing class c)}} \right)$

**Note:** As mentioned in the implementation details in the supplement, we clamped the value to be at least 1, to slow down the diffusion *without speeding up* the transition.

### Example:
- The class 'bottle' appears in 1,243 images within a training set of 28,000 total images.
$\phi_{\text{bottle}} = \log\frac{28000}{1243}$
